config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "homepages#index"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    resource :users, except: :destroy do
      member do
        get :change_password
        patch :update_change_password
      end
    end
    resources :homepages
    resources :account_activations, only: :edit
    resources :password_resets, except: [:index, :show, :destroy]
    resources :jobs
    resources :manages
    resources :products
    resources :invoices
  end
end

app/controllers/homepages_controller.rb
class HomepagesController < ApplicationController
  def index
    @jobs = Job.all.limit 12
  end

  def show
    @job = Job.find_by id: params[:id]
  end
end

app/views/homepages/_job.html.erb
<%= link_to homepage_path(id: job.id) do %>
  <div class="col-md-4 card project-wrap p-3 mb-0 border-0">
    <%= image_tag job.job_image, class:"card-img-top img" %>
    <div class="card-body">
      <h5 class="card-title"><%= job.title %></h5>
      <p class="card-text"><span class="font-weight-bold"><%= t "job.salary" %>: </span> <%= t("price", price: exchange_money(job.salary)) %></p>
      <p class="card-text"><span class="font-weight-bold"><%= t "job.date" %>: </span> <%= l(job.date,format: :notime) %></p>
      <p class="card-text"><span class="font-weight-bold"><%= t "job.quantity" %>: </span><%= job.number_of_staffs %></p>
      <div class="text-center"><%= link_to t("btn.apply"), "#", class: "btn btn-primary" %></div>
    </div>
  </div>
<% end %>

app/views/homepages/index.html.erb
<%= render "common/header" %>

<div class="hero-wrap js-fullheight d-sm-none d-lg-block">
  <div class="overlay js-fullheight"></div>
  <div class="container">
    <div class="row slider-text js-fullheight align-items-center" data-scrollax-parent="true">
      <div class="col-md-7">
        <h1><%= t "index.title" %></h1>
        <span class="subheading"><%= t "index.slogan" %></span>
      </div>
      <% if current_user.blank?%>
        <div class="col-md-4 create-cv ml-auto">
          <div class="subheading"><%= t "index.booking_now" %></div>
          <%= link_to "#", class: "icon-video d-flex align-items-center justify-content-center" do %><!-- change -->
            <span class="fa fa-play"></span>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<section class="ftco-section">
  <div class="container">
    <div class="row justify-content-center pb-4">
      <div class="col-md-12 heading-section text-center">
        <h2 class="mb-4"><%= t "menu_list.list_job" %></h2>
      </div>
    </div>
    <div id="jobs" class="row">
      <%= render partial: "homepages/job", collection: @jobs %>
    </div>
    <div class="w-100 text-center"><%= link_to t("btn.more"), jobs_path, class: "btn btn-success" %></div>
  </div>
</section>

app/views/homepages/show.html.erb
<%= render "common/header" %>

<div class="hero-wrap d-sm-none d-lg-block" style="height: 75px">
  <div class="overlay" style="height: 75px"></div>
</div>

<section class="ftco-section">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <%= image_tag @job.job_image, class:"img-fluid" %>
      </div>
      <div class="col-md-8">
        <h3 class="card-title"><%= @job.title %></h3>
        <p class="card-text"><span class="font-weight-bold"><%= t "job.salary" %>: </span> <%= t("price", price: exchange_money(@job.salary)) %></p>
        <p class="card-text"><span class="font-weight-bold"><%= t "job.date" %>: </span> <%= l(@job.date,format: :notime) %></p>
        <p class="card-text"><span class="font-weight-bold"><%= t "job.quantity" %>: </span><%= @job.number_of_staffs %></p>
        <div class="text-center"><%= link_to t("btn.apply"), "#", class: "btn btn-primary" %></div>
      </div>
    </div>
    <div class="row mt-5">
      <h5 class="font-weight-bold">
        <%= t "space.description" %>
      </h5>
      <br>
      <%= @job.description %>
    </div>
  </div>
</section>