config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "homepages#index"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    resource :users, except: :destroy do
      member do
        get :change_password
        patch :update_change_password
      end
    end
    resources :homepages
    resources :account_activations, only: :edit
    resources :password_resets, except: [:index, :show, :destroy]
    resources :jobs
    resources :manages
    resources :products
    resources :invoices
  end
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save :downcase_email
  before_create :create_activation_digest

  has_many :jobs
  has_many :products
  has_many :invoices, through: :products
  has_one_attached :avatar

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze

  include BCrypt

  validates :full_name, presence: true
  validates :email, presence: true,
    length: {maximum: Settings.user.email.max_length},
    format: {with: VALID_EMAIL_REGEX}
  validates :password, presence: true,
    length: {minimum: Settings.user.password.min_length},
    allow_nil: true
  validates :phone_number, presence: true,
    length: {minimum: Settings.user.phone.min_length,
             maximum: Settings.user.phone.max_length}
  validates :date_of_birth, presence: true
  validates :address, presence: true

  enum role: {admin: 0, renter: 1, freelancer: 2}
  enum activated: {blocked: false, actived: true}

  has_secure_password

  def self.digest string
    cost = if ActiveModel::SecurePassword.min_cost
             Engine::MIN_COST
           else
             Engine.cost
           end
    Password.create string, cost: cost
  end

  class << self
    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  def remember
    self.remember_token = User.new_token
    update remember_digest: User.digest(remember_token)
  end

  def authenticated? attribute, token
    digest = send "#{attribute}_digest"
    return false unless digest

    Password.new(digest).is_password? token
  end

  def forget
    update remember_digest: nil
  end

  def active
    update activated: true, activated_at: Time.zone.now
  end

  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  def create_reset_digest
    self.reset_token = User.new_token
    update reset_digest: User.digest(reset_token),
           reset_sent_at: Time.zone.now
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  private

  def downcase_email
    email.downcase!
  end

  def create_activation_digest
    self.activation_token = User.new_token
    self.activation_digest = User.digest(activation_token)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :get_user, only: [:edit, :update,
                                  :change_password, :update_change_password]

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      @user.send_activation_email
      flash[:info] = t "account.check_email"
      redirect_to root_url
    else
      flash[:danger] = t "account.create_fail"
      render :new
    end
  end

  def edit; end

  def change_password; end

  def update
    if current_user.update update_user_params
      flash[:success] = t "account.profile_updated"
      if current_renter?
        redirect_to manages_path
      else
        redirect_to root_path
      end
    else
      flash.now[:danger] = t "account.update_fail"
      render :edit
    end
  end

  def update_change_password
    if update_password_params[:password].blank?
      flash.now[:danger] = t "reset_passwd.input_passwd"
      render :change_password
    elsif valid_passwd && current_user.update(update_password_params)
      flash[:success] = t "account.passwd_updated"
      redirect_to root_path
    else
      flash.now[:danger] = t "account.change_pwd_fail"
      render :change_password
    end
  end

  private

  def get_user
    @user = current_user
    return if @user

    flash[:warning] = t "account.account_nil"
    redirect_to new_users_path
  end

  def user_params
    params.require(:user)
          .permit :full_name, :email, :password, :password_confirmation,
                  :role, :phone_number, :address, :date_of_birth, :avatar
  end

  def update_user_params
    params.require(:user)
          .permit :full_name, :role, :phone_number, :address,
                  :date_of_birth, :avatar
  end

  def update_password_params
    params.require(:user)
          .permit :password, :password_confirmation
  end

  def valid_passwd
    current_user&.authenticate params[:user][:old_password]
  end
end

app/views/users/change_password.erb
<section class="bg-gradient-primary js-fullheight">
  <div class="container">
    <!-- Outer Row -->
    <div class="row justify-content-center">
      <div class="col-xl-10 col-lg-12 col-md-9">
        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
              <div class="col-lg-6">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4"><%= t "menu_list.login" %></h1>
                  </div>
                  <%= form_for @user, url: update_change_password_users_path do |f| %>
                    <div class="signin-form">
                      <div id="register-form-1" class="row justify-content-center">
                        <div class="col-md-6 col-lg-4">
                          <div class="form-group">
                            <%= f.password_field :old_password, class: "form-control", placeholder: "#{t("update.old_passwd")}" %>
                            <span class="toggle-password" toggle="#user_old_password"><i class="eye-pic fa fa-fw fa-eye field-icon"></i></span>
                          </div>
                          <div class="form-group">
                            <%= f.password_field :password, class: "form-control", placeholder: "#{t("login.passwd")}" %>
                            <span class="toggle-password" toggle="#user_password"><i class="eye-pic fa fa-fw fa-eye field-icon"></i></span>
                          </div>
                          <div class="form-group">
                            <%= f.password_field :password_confirmation, class: "form-control", placeholder: "#{t("register.passwd_conf")}" %>
                            <span class="toggle-password" toggle="#user_password_confirmation"><i class="eye-pic fa fa-fw fa-eye field-icon"></i></span>
                          </div>
                          <div class="form-group">
                            <%= f.submit t("update.update_passwd"), class: "form-control btn btn-primary submit px-3" %>
                          </div>
                        </div>
                      </div>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/users/edit.html.erb
<section class="bg-gradient-primary js-fullheight">
  <div class="container">
    <!-- Outer Row -->
    <div class="row justify-content-center">
      <div class="col-xl-10 col-lg-12 col-md-9">
        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
              <div class="col-lg-6">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4"><%= t "menu_list.edit_profile" %></h1>
                  </div>
                  <%= form_for @user, url: users_path do |f| %>
                    <div class="signin-form">
                      <div class="row">
                        <div class="col-12 text-center">
                          <%= f.label :avatar do%>
                            <%= f.file_field :avatar, accept:"image/*", class:"d-none" %>
                            <% if current_user.avatar.attached? %>
                              <%= image_tag(current_user.avatar, alt: current_user.full_name, id:"output_image", class:"img-avt") %>
                            <% else %>
                              <%= image_tag("avatars/user-avt.png", alt: current_user.full_name, id:"output_image", class:"img-avt") %>
                            <% end %>
                          <% end %>
                        </div>
                        <div class="col-md-6">
                          <div class="form-group">
                            <%= f.text_field :full_name, class: "form-control", placeholder: "#{t("register.full_name")}" %>
                          </div>
                          <div class="form-group">
                            <%= f.select :role, [[t("register.roles.renter"), :renter], [t("register.roles.freelancer"), :freelancer]], {}, class: "form-control" %>
                          </div>
                        </div>
                        <div class="col-md-6">
                          <div class="form-group">
                            <%= f.text_field :phone_number, class: "form-control", placeholder: "#{t("register.phone")}" %>
                          </div>
                          <div class="form-group">
                            <%= f.date_field :date_of_birth, class: "form-control" %>
                          </div>
                        </div>
                      </div>
                      <div class="row">
                        <div class="col-md-12">
                          <div class="form-group">
                            <%= f.text_field :address, class: "form-control", placeholder: "#{t("register.address")}" %>
                          </div>
                        </div>
                      </div>
                      <div class="form-group row">
                        <%= link_to t("btn.close"), root_path, class: "form-control btn btn-white col-5 mx-auto" %>
                        <%= f.submit t("update.btn"), class: "form-control btn btn-primary submit px-3 col-5 mx-auto" %>
                      </div>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/users/new.html.erb
<section class="bg-gradient-primary js-fullheight">
  <div class="container">
    <!-- Outer Row -->
    <div class="row justify-content-center">
      <div class="col-xl-10 col-lg-12 col-md-9">
        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
              <div class="col-lg-6">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4"><%= t "menu_list.register" %></h1>
                  </div>
                  <%= form_for @user, url: users_path do |f| %>
                    <div class="signin-form">
                      <div id="register-form-1" class="row justify-content-center">
                        <div class="">
                          <div class="form-group">
                            <%= f.email_field :email, class: "form-control", placeholder: "#{t("login.username")}" %>
                          </div>
                          <div class="form-group">
                            <%= f.password_field :password, class: "form-control", placeholder: "#{t("login.passwd")}" %>
                            <span class="toggle-password" toggle="#user_password"><i class="eye-pic fa fa-fw fa-eye field-icon"></i></span>
                          </div>
                          <div class="form-group">
                            <%= f.password_field :password_confirmation, class: "form-control", placeholder: "#{t("register.passwd_conf")}" %>
                            <span class="toggle-password" toggle="#user_password_confirmation"><i class="eye-pic fa fa-fw fa-eye field-icon"></i></span>
                          </div>
                          <div class="form-group">
                            <span id="btn-register-next" class="form-control btn btn-primary"><%= t "register.btn_next" %></span>
                          </div>
                        </div>
                      </div>
                      <div id="register-form-2" class="d-none">
                        <div class="row">
                          <div class="col-12 text-center">
                            <%= f.label :avatar do%>
                              <%= f.file_field :avatar, accept:"image/*", class:"d-none" %>
                              <%= image_tag "avatars/user-avt.png", id:"output_image", class:"img-avt" %>
                            <% end %>
                          </div>
                          <div class="col-md-12">
                            <div class="form-group">
                              <%= f.text_field :full_name, class: "form-control", placeholder: "#{t("register.full_name")}" %>
                            </div>
                          </div>
                          <div class="col-md-6">
                            <div class="form-group">
                              <%= f.text_field :phone_number, class: "form-control", placeholder: "#{t("register.phone")}" %>
                            </div>
                          </div>
                          <div class="col-md-6">
                            <div class="form-group">
                              <%= f.date_field :date_of_birth, class: "form-control" %>
                            </div>
                          </div>
                        </div>
                        <div class="row">
                          <div class="col-md-12">
                            <div class="form-group">
                              <%= f.text_field :address, class: "form-control", placeholder: "#{t("register.address")}" %>
                            </div>
                          </div>
                        </div>
                        <div class="form-group row">
                          <span id="btn-register-prev" class="form-control btn btn-white col-5 mx-auto"><%= t "register.btn_prev" %></span>
                          <%= f.submit t("menu_list.register"), class: "form-control btn btn-primary submit px-3 col-5 mx-auto" %>
                        </div>
                      </div>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>