config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "homepages#index"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    resource :users, except: :destroy do
      member do
        get :change_password
        patch :update_change_password
      end
    end
    resources :homepages
    resources :account_activations, only: :edit
    resources :password_resets, except: [:index, :show, :destroy]
    resources :jobs
    resources :manages
    resources :products
    resources :invoices
  end
end

app/views/common/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t "account.sign_up_errors", count: object.errors.count %>
    </div>

    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/common/_flash.html.erb
<div class="container flash">
  <% flash.each do |message_type, message| %>
    <div class="mb-0 alert alert-<%= message_type %>">
      <%= message %>
    </div>
  <% end %>
</div>

app/views/common/_footer.html.erb
<footer class="sticky-footer bg-white">
  <div class="container my-auto">
    <div class="copyright text-center my-auto">
      <span>Copyright &copy; Pham Le Hoan 2021</span>
    </div>
  </div>
</footer>

app/views/common/_header.html.erb
<%= render "common/flash" %>
<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar ftco-navbar-light" id="ftco-navbar">
  <div class="container">
    <%= link_to root_path, class: "navbar-brand" do %>
      iWork
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav"
			aria-expanded="false" aria-label="Toggle navigation">
      <span class="oi oi-menu"></span> <%= t "menu_list.menu" %>
    </button>
    <div class="collapse navbar-collapse" id="ftco-nav">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item <%= current_class?("homepages") %>"><%= link_to t("menu_list.home"), root_path, class:"nav-link" %></li>
        <li class="nav-item dropdown">
          <%= link_to "#", class: "nav-link dropdown-toggle", "data-toggle": "dropdown" do %>
            <%= t "menu_list.languages.language" %>
            <b class="caret"></b>
          <% end %>
          <ul class="dropdown-menu p-3">
            <li class="nav-item">
              <%= link_to locale: :en do %>
                <%= image_tag("languages/EN.png", alt: t("menu_list.languages.english"), class: "img-lang") %>
                <%= t "menu_list.languages.english" %>
              <% end %>
            </li>
            <hr>
            <li class="nav-item">
              <%= link_to locale: :vi do %>
                <%= image_tag("languages/VN.png", alt: t("menu_list.languages.vietnamese"), class: "img-lang") %>
                <%= t "menu_list.languages.vietnamese" %>
              <% end %>
            </li>
          </ul>
        </li>
        <% if logged_in? %>
          <li class="nav-item dropdown">
            <%= link_to "#", class:"nav-link dropdown-toggle", "data-toggle": "dropdown" do %>
              <% if current_user.avatar.attached? %>
                <%= image_tag(current_user.avatar, alt: current_user.full_name, class: "rounded-circle img-avt") %>
              <% else %>
                <%= image_tag("avatars/user-avt.png", alt: current_user.full_name, class: "rounded-circle img-avt") %>
              <% end %>
            <% end %>
            <ul class="dropdown-menu p-3">
              <li class="nav-item text-center">
                <% if current_user.avatar.attached? %>
                  <%= image_tag(current_user.avatar, alt: current_user.full_name, class: "rounded-circle img-avt-sm") %>
                <% else %>
                  <%= image_tag("avatars/user-avt.png", alt: current_user.full_name, class: "rounded-circle img-avt-sm") %>
                <% end %>
              </li>
              <li class="nav-item text-center">
                <strong><%= current_user.full_name %></strong>
                <small><%= current_user.email %></small>
              </li>
              <hr>
              <li class="nav-item text-center"><%= link_to t("menu_list.edit_profile"), edit_users_path, class:"btn btn-primary w-100 mb-2" %></li>
              <li class="nav-item text-center"><%= link_to t("update.update_passwd"), change_password_users_path, class:"btn btn-primary w-100 mb-2" %></li>
              <li class="nav-item text-center"><%= link_to t("menu_list.logout"), logout_path, class:"btn btn-primary w-100", method: :delete %></li>
            <ul>
          </li>
        <% else %>
          <li class="nav-item <%= current_class?("sessions") %>"><%= link_to t("menu_list.login"), login_path, class:"nav-link" %></li>
          <li class="nav-item <%= current_class?("users") %> cta ml-4"><%= link_to t("menu_list.register"), new_users_path, class:"nav-link" %></li>
        <% end %>
      </li>
    </div>
  </div>
</nav>
<!-- END nav -->

app/views/common/_left_bar.html.erb
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
  <!-- Sidebar - Brand -->
  <a class="sidebar-brand d-flex align-items-center justify-content-center" href="/">
    <div class="sidebar-brand-icon">
      <%= image_tag "favicon.ico", style:"width: 30px; background-color: white", class:"p-1 rounded" %>
    </div>
    <div class="sidebar-brand-text mx-3">iWork</div>
  </a>
  <!-- Divider -->
  <hr class="sidebar-divider my-0">
  <!-- Nav Item - Dashboard -->
  <li class="nav-item active">
    <a class="nav-link" href="/manages">
      <i class="fas fa-fw fa-tachometer-alt"></i>
      <span>Báo cáo hoạt động</span></a>
  </li>
  <!-- Divider -->
  <hr class="sidebar-divider">
  <!-- Heading -->
  <div class="sidebar-heading">
    Giao diện
  </div>
  <li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
                    aria-expanded="true" aria-controls="collapseTwo">
      <i class="fas fa-fw fa-cog"></i>
      <span>Hàng hóa</span>
    </a>
    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
      <div class="bg-white py-2 collapse-inner rounded">
        <h6 class="collapse-header">Quản lý sản phẩm</h6>
        <%= link_to "Danh sách sản phẩm", products_path, class:"collapse-item"%>
        <a class="collapse-item" href="cards.html">Thêm mới sản phẩm</a>
      </div>
    </div>
  </li>
  <li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities"
                    aria-expanded="true" aria-controls="collapseUtilities">
      <i class="fas fa-fw fa-file-alt"></i>
      <span>Hóa đơn</span>
    </a>
    <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities"
                    data-parent="#accordionSidebar">
      <div class="bg-white py-2 collapse-inner rounded">
        <h6 class="collapse-header">Quản lý doanh thu</h6>
        <%= link_to "Danh sách hóa đơn", invoices_path, class:"collapse-item"%>
        <a class="collapse-item" href="utilities-border.html">Tạo mới hóa đơn</a>
      </div>
    </div>
  </li>
  <li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseJobs"
                    aria-expanded="true" aria-controls="collapseJobs">
      <i class="fas fa-fw fa-wrench"></i>
      <span>Công việc</span>
    </a>
    <div id="collapseJobs" class="collapse" aria-labelledby="headingUtilities"
                    data-parent="#accordionSidebar">
      <div class="bg-white py-2 collapse-inner rounded">
        <h6 class="collapse-header">Công việc tôi thuê</h6>
        <%= link_to "Danh sách công việc", jobs_path, class:"collapse-item"%>
        <%= link_to "Thêm mới công việc", new_job_path, class:"collapse-item" %>
        <a class="collapse-item" href="utilities-border.html">Danh sách ứng tuyển</a>
      </div>
    </div>
  </li>
  <!-- Divider -->
  <hr class="sidebar-divider">
  <!-- Nav Item - Tables -->
  <li class="nav-item">
    <a class="nav-link" href="tables.html">
      <i class="fas fa-fw fa-table"></i>
      <span>Livestream</span></a>
  </li>
  <!-- Nav Item - Tables -->
  <li class="nav-item">
    <a class="nav-link" href="tables.html">
      <i class="fas fa-fw fa-table"></i>
      <span>Ví của tôi</span></a>
  </li>
</ul>

app/views/common/_top_bar.html.erb
<%= render "common/flash" %>
<!-- Topbar -->
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
  <!-- Sidebar Toggle (Topbar) -->
  <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
    <i class="fa fa-bars"></i>
  </button>
  <!-- Topbar Search -->
  <form
                        class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
    <div class="input-group">
      <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
                                aria-label="Search" aria-describedby="basic-addon2">
      <div class="input-group-append">
        <button class="btn btn-primary" type="button">
          <i class="fas fa-search fa-sm"></i>
        </button>
      </div>
    </div>
  </form>
  <!-- Topbar Navbar -->
  <ul class="navbar-nav ml-auto">
    <!-- Nav Item - Search Dropdown (Visible Only XS) -->
    <li class="nav-item dropdown no-arrow d-sm-none">
      <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-search fa-fw"></i>
      </a>
      <!-- Dropdown - Messages -->
      <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                                aria-labelledby="searchDropdown">
        <form class="form-inline mr-auto w-100 navbar-search">
          <div class="input-group">
            <input type="text" class="form-control bg-light border-0 small"
                                            placeholder="Search for..." aria-label="Search"
                                            aria-describedby="basic-addon2">
            <div class="input-group-append">
              <button class="btn btn-primary" type="button">
                <i class="fas fa-search fa-sm"></i>
              </button>
            </div>
          </div>
        </form>
      </div>
    </li>
    <!-- Nav Item - Alerts -->
    <li class="nav-item dropdown no-arrow mx-1">
      <%= link_to "#", class: "nav-link dropdown-toggle", "data-toggle": "dropdown" do %>

        <% if I18n.locale == "vi" %>
            <%= image_tag("languages/EN.png", alt: t("menu_list.languages.english"), style: "width:30px") %>
        <% else %>
            <%= image_tag("languages/VN.png", alt: t("menu_list.languages.english"), style: "width:30px") %>
        <% end %>

        <b class="caret"></b>
      <% end %>
      <ul class="dropdown-menu p-3">
        <li class="nav-item">
          <%= link_to locale: :en do %>
            <%= image_tag("languages/EN.png", alt: t("menu_list.languages.english"), style: "width:30px") %>
            <%= t "menu_list.languages.english" %>
          <% end %>
        </li>
        <hr>
        <li class="nav-item">
          <%= link_to locale: :vi do %>
            <%= image_tag("languages/VN.png", alt: t("menu_list.languages.vietnamese"), style: "width:30px") %>
            <%= t "menu_list.languages.vietnamese" %>
          <% end %>
        </li>
      </ul>
    </li>
    <div class="topbar-divider d-none d-sm-block"></div>
    <!-- Nav Item - User Information -->
    <li class="nav-item dropdown no-arrow">
      <% if logged_in? %>
        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                                  data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span class="mr-2 d-none d-lg-inline text-gray-600 small"><%= current_user.full_name %></span>
          <%= image_tag current_user.avatar, class:"img-profile rounded-circle" %>
        </a>
      <% else %>
        <%= link_to "Login", login_path, class:"nav-link" %>
      <% end %>
      <!-- Dropdown - User Information -->
      <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                aria-labelledby="userDropdown">
        <ul class="p-3">
          <li class="nav-item text-center">
            <% if current_user.avatar.attached? %>
              <%= image_tag(current_user.avatar, alt: current_user.full_name, class: "rounded-circle img-avt img-avt-sm") %>
            <% else %>
              <%= image_tag("avatars/user-avt.png", alt: current_user.full_name, class: "rounded-circle img-avt img-avt-sm") %>
            <% end %>
          </li>
          <li class="nav-item text-center">
            <strong><%= current_user.full_name %></strong>
            <small><%= current_user.email %></small>
          </li>
          <hr>
          <li class="nav-item text-center"><%= link_to t("menu_list.edit_profile"), edit_users_path, class:"btn btn-primary w-100 mb-2" %></li>
          <li class="nav-item text-center"><%= link_to t("update.update_passwd"), change_password_users_path, class:"btn btn-primary w-100 mb-2" %></li>
          <li class="nav-item text-center"><%= link_to t("menu_list.logout"), logout_path, class:"btn btn-primary w-100", method: :delete %></li>
        <ul>
    </li>
  </ul>
</nav>
<!-- End of Topbar -->
<!-- Logout Modal-->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
      <div class="modal-footer">
        <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
        <%= link_to t("menu_list.logout"), logout_path, class:"btn btn-primary", method: :delete %>
      </div>
    </div>
  </div>
</div>